### ISSUE TITLE
qtype&maxsize組み合わせ不可

### ISSUE THREAD

**Issue by t0r0t0r0** [mimuret/iptables-ext-dns#12]
## OK

-A HEAD -i eth0 -p udp -m udp --dport 53 -m dns --rmatch --qname example.jp --rd -j LOG
-A HEAD -i eth0 -p udp -m udp --dport 53 -m dns --rmatch --qname example.jp --qtype A -j LOG
-A HEAD -i eth0 -p udp -m udp --dport 53 -m dns --rmatch --qname example.jp --rd --qtype A -j LOG
## NG

-A HEAD -i eth0 -p udp -m udp --dport 53 -m dns --rmatch --qname example.jp ! --maxsize 12 --rd --qtype A -j LOG

組み合わせチェック
maxsizeとqtypeの組み合わせだとmaxsizeが効かない。

**Comment by mimuret** [comment]
invflagがうまく動いていなかったようです。
あとmaxsize単独で使用した場合、動作しなかったバグがありました。

**Comment by t0r0t0r0** [comment]
正常動作確認しました。
