### ISSUE TITLE
Wrong directory for installation?

### ISSUE THREAD

**Issue by bortzmeyer** [mimuret/iptables-ext-dns#7]
```
% sudo iptables -A INPUT  -m dns --rmatch --qname pizza \! --maxsize 10 -j DROP
iptables v1.6.0: Couldn't load match `dns':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```

Running it with strace shows that it tries to load a library from `/lib./xtables`:

```
stat64("/lib/xtables/libipt_dns.so", 0xbfd04730) = -1 ENOENT (No such file or directory)
stat64("/lib/xtables/libxt_dns.so", 0xbfd04730) = -1 ENOENT (No such file or directory)
```

And does not use the directoty where `make install` copied its library (`/usr/bin/install -c -m 0755 -o root -g root xt_dns.ko /lib/modules/4.3.0-1-686-pae/kernel/net/netfilter/xt_dns.ko` ) I assume this is the kernel module. This one is loaded without error:

```
% lsmod | grep dns
xt_dns                 16384  0
x_tables               20480  1 xt_dns
```

May be `make install` should copy an userland library as well, to `/lib/xtables` ?

Debian testing "stretch", kernel 4.3.0-1-686-pae

**Comment by mimuret** [comment]
use --libdir option.

```
./configure --libdir=/lib
```

**Comment by bortzmeyer** [comment]
Thanks, it is a bit better but not perfect. Code is installed in `/lib/xtables` but:

```
iptables: match "dns" has version "libxtables.so.10", but "libxtables.so.11" is required.
```

**Comment by bortzmeyer** [comment]
I don't know why but `make distclean&& ./configure --libdir=/lib && make` solved this last problem. I can now define iptables rules:

```
 sudo ip6tables -n -v -L OUTPUT
Chain OUTPUT (policy ACCEPT 2162 packets, 243K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      *       ::/0                 ::/0                dns --qname pizza 
    0     0 LOG        all      *      *       ::/0                 ::/0                dns --qtype ANY  LOG flags 0 level 4
```

**Comment by mimuret** [comment]
Congratulation!!
Can you add Debian install document ?
https://github.com/mimuret/iptables-ext-dns/wiki/install
